(window.webpackJsonp=window.webpackJsonp||[]).push([[432],{"./manual/Ruby/Ruby-Error-Handling.md":function(e,n,r){"use strict";r.r(n),r.d(n,"default",function(){return i});var a=r("./node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/objectWithoutProperties.js"),t=(r("./node_modules/react/index.js"),r("./node_modules/@mdx-js/react/dist/index.es.js")),s={},o="wrapper";function i(e){var n=e.components,r=Object(a.a)(e,["components"]);return Object(t.b)(o,Object.assign({},s,r,{components:n,mdxType:"MDXLayout"}),Object(t.b)("h1",{id:"ruby-error-handling"},"Ruby Error Handling"),Object(t.b)("p",null,"This is a basic example of raising and exception and rescueing the thrown exception."),Object(t.b)("pre",null,Object(t.b)("code",Object.assign({parentName:"pre"},{className:"language-ruby"}),"def raise_and_rescue\n  begin\n    puts 'I am before the raise.'\n    raise 'An error has occured.'\n    puts 'I am after the raise.'\n  rescue\n    puts 'I am rescued.'\n  end\n  puts 'I am after the begin block.'\nend\n")))}i&&i===Object(i)&&Object.isExtensible(i)&&Object.defineProperty(i,"__filemeta",{enumerable:!0,configurable:!0,value:{name:"MDXContent",filename:"manual/Ruby/Ruby-Error-Handling.md"}}),i.isMDXComponent=!0}}]);
//# sourceMappingURL=manual-ruby-ruby-error-handling.101a1afd2417ec7a4a77.js.map